stages:
  - test
  - dist
  - scan

Test:
  stage: test
  script:
    - make test
  tags:
    - linux
  except:
    - tags

Dist:
  stage: dist
  script:
    - make dist
  tags:
    - linux
  only:
    - master
    - dev

Sonar Scan:
  stage: scan
  script:
    - make scan
  tags:
    - linux
  only:
    - master
    - dev
